### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by SakshiShreya** [SakshiShreya/first-step-pharma-fe#1]
Pull request should have all these points

- [x] Install router
- [ ] Add routing to browser

**Comment by SakshiShreya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Initial setup](https://trello.com/c/WaLnDxIg/6-initial-setup)

**Comment by krishna1212031** [comment]
not needed

**Comment by krishna1212031** [comment]
not needed
